# Generated by Django 6.0.6 on 2026-07-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharsErha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='mitban_nvl/', verbose_name="insert character's photo")),
                ('name', models.CharField(max_length=30, verbose_name="enter character's name")),
                ('age', models.PositiveBigIntegerField(default=26, verbose_name="enter character's sge")),
                ('organization', models.CharField(choices=[('Sisheng Peak', 'Sisheng Peak'), ('Wubei Temple', 'Wubei Temple'), ('Shangqing Pavillion', 'Shangqing Pavillion'), ('Guyueye Sect', 'Guyueye Sect'), ('Taobao Mountain', 'Taobao Mountain'), ('Unknown', 'Unknown')], default='Unknown', max_length=100, verbose_name="Enter character's sect/organization")),
                ('description', models.TextField(verbose_name="Enter character's background")),
                ('weapon', models.CharField(max_length=100, verbose_name="Enter character's weapon")),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
