# Generated by Django 6.0.6 on 2026-07-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charserha',
            options={'verbose_name': 'character', 'verbose_name_plural': 'characters'},
        ),
    ]
