# Generated by Django 6.0.6 on 2026-07-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erha', '0002_alter_charserha_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fragments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Enter chapter's title")),
                ('passage', models.TextField(verbose_name='Enter content')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
            },
        ),
    ]
