# Generated by Django 6.0.6 on 2026-07-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erha', '0003_fragments'),
    ]

    operations = [
        migrations.AddField(
            model_name='charserha',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
